"""Content for the JavaScript Essentials workbook.

Each topic is a sheet. Rows follow the same five columns:
    Concept | What it does | Example | Result / Output | Notes and gotchas
Keeping the data here means generate_sheets.py stays about formatting only.
"""

COLUMNS = ["Concept", "What it does", "Example", "Result / Output", "Notes and gotchas"]

TOPICS = [
    (
        "01 Variables and Scope",
        "How values are named, where those names are visible, and when they exist.",
        [
            ["let", "Declares a block-scoped variable you can reassign.", "let count = 0; count = 1;", "count is 1", "Default choice when the value changes."],
            ["const", "Declares a block-scoped binding you cannot reassign.", "const PI = 3.14;", "PI is 3.14", "The binding is fixed, the value is not. const obj = {}; obj.a = 1 is legal."],
            ["var", "Function-scoped, hoisted, legacy declaration.", "function f() { var x = 1; }", "x visible in the whole function", "Avoid in new code. Leaks out of if and for blocks."],
            ["Block scope", "A name declared with let or const lives only inside its { }.", "if (true) { let a = 1; } // a is gone here", "ReferenceError outside the block", "var would have leaked out of the block instead."],
            ["Hoisting", "Declarations are registered before code runs.", "console.log(v); var v = 2;", "undefined", "var is hoisted and initialised to undefined, so it does not throw."],
            ["Temporal Dead Zone", "let and const exist but are unusable before their declaration line.", "console.log(l); let l = 2;", "ReferenceError", "The TDZ is what makes let feel safer than var."],
            ["Shadowing", "An inner scope may reuse an outer name.", "let n = 1; { let n = 2; } // inner n is 2", "Outer n stays 1", "Handy, but heavy shadowing makes code hard to follow."],
            ["Global scope", "Names declared outside any function or block.", "const APP = 'cv';", "Reachable everywhere", "In browsers, var globals attach to window; let and const do not."],
            ["Closure", "An inner function keeps access to the scope it was created in.", "function counter() { let c = 0; return () => ++c; }", "Each call returns 1, 2, 3...", "The basis of private state, module patterns, and most callbacks."],
            ["Loop capture", "let gives each loop iteration its own binding.", "for (let i = 0; i < 3; i++) setTimeout(() => console.log(i));", "0 1 2", "With var the same code logs 3 3 3, the classic interview trap."],
            ["Strict mode", "Opts a file or function into stricter parsing rules.", "'use strict';", "Assigning to an undeclared name throws", "ES modules are always in strict mode automatically."],
        ],
    ),
    (
        "02 Types and Coercion",
        "The seven primitives, objects, and the conversion rules that surprise people.",
        [
            ["string", "Text. Immutable once created.", "const s = 'hi';", "typeof s is 'string'", "Single quotes, double quotes, and backticks all build strings."],
            ["number", "One numeric type, a 64-bit float, for integers and decimals alike.", "const n = 42; const f = 1.5;", "typeof n is 'number'", "No separate int type. Safe integers stop at 2^53 - 1."],
            ["bigint", "Integers beyond the safe number range.", "const big = 9007199254740993n;", "typeof big is 'bigint'", "Cannot be mixed with number in arithmetic without explicit conversion."],
            ["boolean", "true or false.", "const ok = true;", "typeof ok is 'boolean'", "Comparisons and logical operators produce these."],
            ["undefined", "A variable declared but never given a value.", "let u; console.log(u);", "undefined", "Also what a function returns when it has no return statement."],
            ["null", "A deliberate empty value.", "const empty = null;", "typeof null is 'object'", "That typeof result is a famous bug in the language, kept for compatibility."],
            ["symbol", "A unique key, mostly for library-level object properties.", "const id = Symbol('id');", "Always unique", "Two symbols with the same description are still different."],
            ["object", "Everything else: plain objects, arrays, functions, dates, maps.", "const o = { a: 1 }; const arr = [1, 2];", "typeof both is 'object'", "typeof a function returns 'function', the one exception."],
            ["typeof", "Reports the primitive type of a value as a string.", "typeof 'a'", "'string'", "Unreliable for null and arrays. Use Array.isArray for arrays."],
            ["Truthy and falsy", "Every value converts to a boolean in a condition.", "if ('') { } // never runs", "Skipped", "Falsy values: false, 0, -0, 0n, '', null, undefined, NaN. Everything else is truthy."],
            ["== loose equality", "Compares after converting the operands.", "'5' == 5", "true", "Coercion rules are subtle. Prefer === in almost all code."],
            ["=== strict equality", "Compares type and value with no conversion.", "'5' === 5", "false", "The default you should reach for."],
            ["NaN", "Not-a-Number, the result of an invalid numeric operation.", "Number('abc')", "NaN", "NaN is not equal to itself. Test it with Number.isNaN."],
            ["Number()", "Converts a value to a number explicitly.", "Number('12.5')", "12.5", "Number('') is 0, which trips up empty form fields."],
            ["parseInt / parseFloat", "Reads a number from the front of a string.", "parseInt('12px', 10)", "12", "Always pass the radix 10 to parseInt."],
            ["String() and template", "Converts a value to text.", "String(12) or `${12}`", "'12'", "Template literals are usually the more readable option."],
        ],
    ),
    (
        "03 Operators",
        "Arithmetic, comparison, logic, and the modern shorthands worth knowing.",
        [
            ["+ - * /", "Standard arithmetic.", "7 / 2", "3.5", "Division always produces a float, never an integer."],
            ["%", "Remainder after division.", "7 % 2", "1", "Common evenness test: n % 2 === 0."],
            ["**", "Exponentiation.", "2 ** 10", "1024", "Replaces Math.pow in modern code."],
            ["++ and --", "Increment or decrement by one.", "let i = 1; i++;", "i is 2", "Prefix ++i returns the new value, postfix i++ returns the old one."],
            ["+ on strings", "Concatenates when either side is a string.", "'1' + 2", "'12'", "The single biggest source of accidental coercion bugs."],
            ["Comparison", "Less than, greater than, and their or-equal forms.", "3 < 5", "true", "Comparing strings uses character codes, so '10' < '9' is true."],
            ["&& logical AND", "Returns the first falsy operand, or the last one.", "true && 'yes'", "'yes'", "Returns a value, not necessarily a boolean. Short-circuits."],
            ["|| logical OR", "Returns the first truthy operand, or the last one.", "'' || 'fallback'", "'fallback'", "Careless as a default: 0 and '' trigger the fallback too."],
            ["?? nullish coalescing", "Falls back only for null or undefined.", "0 ?? 10", "0", "The correct default operator when 0 or '' are valid values."],
            ["?. optional chaining", "Reads a property only if the target exists.", "user?.address?.city", "undefined instead of a throw", "Stops the 'cannot read property of undefined' crash."],
            ["! logical NOT", "Flips truthiness to a boolean.", "!0", "true", "!!value is a short idiom for converting to a real boolean."],
            ["Ternary", "A conditional expression.", "const label = n > 0 ? 'pos' : 'neg';", "'pos' when n is 1", "Great for one choice, unreadable when nested."],
            ["Spread ...", "Expands an iterable into elements or properties.", "const copy = [...arr]; const merged = { ...a, ...b };", "New array / new object", "A shallow copy only. Nested objects stay shared."],
            ["Rest ...", "Collects the remaining items into an array.", "function sum(...nums) { }", "nums is an array", "Same three dots, opposite direction, depending on position."],
            ["Destructuring", "Pulls values out of arrays and objects into names.", "const { a, b = 2 } = obj; const [x, y] = arr;", "a, b, x, y bound", "Supports defaults, renaming with a: newName, and nesting."],
            ["Logical assignment", "Assigns only when a condition holds.", "opts.mode ??= 'light';", "Sets only when nullish", "Also &&= and ||=. Concise, but keep it readable."],
        ],
    ),
    (
        "04 Strings",
        "The methods you reach for daily. Strings are immutable, so each returns a new string.",
        [
            [".length", "Number of characters.", "'hello'.length", "5", "A property, not a method, so no parentheses."],
            [".toUpperCase / .toLowerCase", "Changes case.", "'Hi'.toUpperCase()", "'HI'", "Use lowercase on both sides for case-insensitive comparison."],
            [".trim()", "Removes whitespace from both ends.", "'  a  '.trim()", "'a'", "Also trimStart and trimEnd. Essential on form input."],
            [".includes()", "Tests whether a substring appears.", "'hello'.includes('ell')", "true", "Clearer than indexOf(...) !== -1."],
            [".startsWith / .endsWith", "Tests the beginning or end.", "'file.js'.endsWith('.js')", "true", "Reads far better than a slice comparison."],
            [".indexOf()", "Position of the first match, or -1.", "'hello'.indexOf('l')", "2", "Returns -1 when absent, which is truthy, so compare explicitly."],
            [".slice()", "Extracts a section by index.", "'javascript'.slice(0, 4)", "'java'", "Accepts negative indexes: slice(-3) takes the last three."],
            [".substring()", "Similar to slice, older.", "'javascript'.substring(0, 4)", "'java'", "Rejects negative indexes and swaps its arguments. Prefer slice."],
            [".replace()", "Replaces the first match.", "'a-b-c'.replace('-', '+')", "'a+b-c'", "Only the first, unless you pass a global regular expression."],
            [".replaceAll()", "Replaces every match.", "'a-b-c'.replaceAll('-', '+')", "'a+b+c'", "Simpler than the /g regex for plain text."],
            [".split()", "Breaks a string into an array.", "'a,b,c'.split(',')", "['a','b','c']", "split('') gives characters. Pairs with array join()."],
            [".repeat()", "Repeats the string.", "'ab'.repeat(3)", "'ababab'", "Useful for separators and simple indentation."],
            [".padStart / .padEnd", "Pads to a target length.", "'7'.padStart(2, '0')", "'07'", "The tidy way to format clocks and ids."],
            [".at()", "Character at an index, negatives allowed.", "'hello'.at(-1)", "'o'", "Cleaner than s[s.length - 1]."],
            ["Template literals", "Interpolation and multi-line text with backticks.", "`Hi ${name}, you are ${age}`", "'Hi Ana, you are 30'", "Any expression fits inside ${ }. Preserves newlines."],
            [".localeCompare()", "Locale-aware comparison for sorting.", "['b','a'].sort((x, y) => x.localeCompare(y))", "['a','b']", "Handles accented characters correctly, unlike raw < comparison."],
        ],
    ),
    (
        "05 Arrays",
        "The workhorse collection. The Notes column marks which methods mutate the original.",
        [
            [".push() / .pop()", "Adds or removes at the end.", "arr.push(4)", "New length returned", "MUTATES. pop returns the removed item."],
            [".unshift() / .shift()", "Adds or removes at the start.", "arr.shift()", "The removed first item", "MUTATES. Slower than push and pop on long arrays."],
            [".slice()", "Copies a section.", "[1,2,3,4].slice(1, 3)", "[2, 3]", "Does not mutate. slice() with no arguments is a shallow copy."],
            [".splice()", "Removes or inserts in place.", "arr.splice(1, 2, 'x')", "Array of removed items", "MUTATES. Easy to confuse with slice, so read carefully."],
            [".concat()", "Joins arrays into a new one.", "[1].concat([2, 3])", "[1, 2, 3]", "Does not mutate. Spread [...a, ...b] is the modern equivalent."],
            [".map()", "Transforms every item into a new array.", "[1,2,3].map(n => n * 2)", "[2, 4, 6]", "Always same length as the source. Do not use it for side effects."],
            [".filter()", "Keeps items that pass a test.", "[1,2,3,4].filter(n => n % 2 === 0)", "[2, 4]", "Returns [] when nothing matches, never undefined."],
            [".reduce()", "Folds the array into a single value.", "[1,2,3].reduce((sum, n) => sum + n, 0)", "6", "Always pass the initial value. Powerful, but a loop is often clearer."],
            [".find() / .findIndex()", "First matching item, or its position.", "users.find(u => u.id === 3)", "The object, or undefined", "find returns undefined when nothing matches, findIndex returns -1."],
            [".some() / .every()", "Tests whether any, or all, items pass.", "[1,2].some(n => n > 1)", "true", "Both short-circuit as soon as the answer is known."],
            [".includes()", "Tests membership.", "[1,2,3].includes(2)", "true", "Uses ===, so it will not find an equal-looking object."],
            [".sort()", "Orders the array.", "[10, 9, 1].sort((a, b) => a - b)", "[1, 9, 10]", "MUTATES, and without a comparator it sorts as text: 10 before 9."],
            [".reverse()", "Reverses the order.", "[1,2,3].reverse()", "[3, 2, 1]", "MUTATES. Copy first with [...arr].reverse() if that matters."],
            [".join()", "Builds a string from the items.", "['a','b'].join('-')", "'a-b'", "Default separator is a comma. The inverse of split."],
            [".flat() / .flatMap()", "Flattens nested arrays.", "[1, [2, [3]]].flat(2)", "[1, 2, 3]", "flatMap is map followed by one level of flatten."],
            [".forEach()", "Runs a function for each item.", "arr.forEach(n => console.log(n))", "undefined", "Returns nothing, and you cannot break out of it. Use for...of when you need to."],
            ["Array.from()", "Builds an array from anything iterable or array-like.", "Array.from({ length: 3 }, (_, i) => i)", "[0, 1, 2]", "The clean way to turn a NodeList into a real array."],
            ["Array.isArray()", "Reliable array check.", "Array.isArray([])", "true", "typeof [] is 'object', so this is the only correct test."],
        ],
    ),
    (
        "06 Objects",
        "Key and value pairs, plus copying rules that catch people out.",
        [
            ["Object literal", "Creates an object.", "const user = { name: 'Ana', age: 30 };", "An object", "Keys are strings or symbols. Values can be anything."],
            ["Dot access", "Reads a known property.", "user.name", "'Ana'", "Preferred when the key is a fixed, valid identifier."],
            ["Bracket access", "Reads a computed or unusual key.", "user['first name'] or user[key]", "The value", "The only option when the key is in a variable."],
            ["Shorthand properties", "Uses a variable name as the key.", "const name = 'Ana'; const u = { name };", "{ name: 'Ana' }", "Saves repetition when building objects from locals."],
            ["Computed keys", "Builds a key from an expression.", "const k = 'id'; const o = { [k]: 1 };", "{ id: 1 }", "Note the brackets inside the literal."],
            ["Object.keys / values / entries", "Lists keys, values, or pairs.", "Object.entries({ a: 1 })", "[['a', 1]]", "entries pairs perfectly with for...of destructuring."],
            ["Destructuring", "Unpacks properties into variables.", "const { name, age = 0 } = user;", "name and age bound", "Rename with { name: userName }, default with = 0."],
            ["Spread copy", "Shallow-copies and merges.", "const merged = { ...defaults, ...options };", "New object", "Later objects win on conflicting keys."],
            ["Shallow vs deep", "A spread copies only the top level.", "const c = { ...o }; c.nested.a = 9;", "o.nested.a is also 9", "Nested objects stay shared. This surprises everyone once."],
            ["structuredClone()", "Real deep copy, built in.", "const deep = structuredClone(obj);", "Fully independent copy", "Handles dates, maps, and sets. Cannot clone functions."],
            ["JSON.stringify / parse", "Converts to and from JSON text.", "JSON.parse(JSON.stringify(o))", "A deep copy", "Old deep-copy trick, but it drops functions, undefined, and dates become strings."],
            ["Optional chaining", "Safely reads a possibly missing path.", "config?.db?.host", "undefined instead of a throw", "Combine with ?? to supply a default."],
            ["in operator", "Tests whether a key exists.", "'name' in user", "true", "True even when the value is undefined, unlike a truthiness check."],
            ["Object.freeze()", "Makes an object read-only.", "Object.freeze(config)", "Writes are ignored", "Shallow. Nested objects remain mutable."],
            ["Map", "A keyed collection with keys of any type.", "const m = new Map(); m.set(obj, 1);", "m.get(obj) is 1", "Keeps insertion order and has a real .size. Use it for dynamic keys."],
            ["Set", "A collection of unique values.", "[...new Set([1, 1, 2])]", "[1, 2]", "The shortest way to de-duplicate an array."],
        ],
    ),
    (
        "07 Functions",
        "Declarations, arrows, closures, and how this gets its value.",
        [
            ["Function declaration", "A named, hoisted function.", "function add(a, b) { return a + b; }", "add(1, 2) is 3", "Fully hoisted, so it can be called above its definition."],
            ["Function expression", "A function stored in a variable.", "const add = function (a, b) { return a + b; };", "Same result", "Not hoisted as a callable, the variable rules apply instead."],
            ["Arrow function", "Short syntax with no own this.", "const add = (a, b) => a + b;", "Implicit return", "A body in braces needs an explicit return."],
            ["Default parameters", "Values used when an argument is missing.", "function greet(name = 'there') { }", "greet() greets 'there'", "Only undefined triggers the default, not null."],
            ["Rest parameters", "Collects extra arguments.", "function sum(...nums) { return nums.length; }", "sum(1,2,3) is 3", "A real array, unlike the old arguments object."],
            ["Returning early", "Exits a function immediately.", "if (!user) return null;", "Skips the rest", "Guard clauses keep nesting shallow and readable."],
            ["Callback", "A function passed to another function.", "arr.map(n => n * 2)", "Transformed array", "The foundation of array methods and event handlers."],
            ["Higher-order function", "Takes or returns a function.", "const twice = f => x => f(f(x));", "twice(n => n + 1)(0) is 2", "Enables composition and reusable behaviour."],
            ["Closure", "Keeps outer variables alive after the outer call returns.", "function make() { let n = 0; return () => ++n; }", "Private counter", "The standard way to model private state."],
            ["IIFE", "A function invoked as soon as it is defined.", "(function () { })();", "Runs immediately", "Was used for scoping before modules existed."],
            ["this in a method", "Refers to the object the method was called on.", "user.greet()", "this is user", "Depends on how it is called, not where it is written."],
            ["this in an arrow", "Inherited from the enclosing scope.", "setTimeout(() => this.tick(), 100)", "this stays the outer one", "Exactly why arrows are preferred inside callbacks."],
            ["call / apply / bind", "Sets this explicitly.", "fn.call(obj, a); const bound = fn.bind(obj);", "Runs with this = obj", "bind returns a new function instead of calling it."],
            ["Pure function", "Same input, same output, no side effects.", "const double = n => n * 2;", "Predictable", "Easiest kind of code to test and to reason about."],
            ["Recursion", "A function that calls itself.", "const fact = n => (n <= 1 ? 1 : n * fact(n - 1));", "fact(5) is 120", "Always write the base case first or the stack overflows."],
        ],
    ),
    (
        "08 Modern Syntax",
        "The ES2015 and later features that define how JavaScript is written today.",
        [
            ["let and const", "Block-scoped declarations.", "const x = 1;", "Safer scoping", "ES2015. var is effectively retired."],
            ["Arrow functions", "Concise functions with lexical this.", "const f = x => x * 2;", "Shorter callbacks", "ES2015. Cannot be used as constructors."],
            ["Template literals", "Interpolated, multi-line strings.", "`Hello ${name}`", "Readable strings", "ES2015. Ends most string concatenation."],
            ["Destructuring", "Unpacks arrays and objects.", "const { id } = res;", "Fewer temporaries", "ES2015. Works in parameter lists too."],
            ["Spread and rest", "Expands or collects values.", "const all = [...a, ...b];", "New array", "ES2015 for arrays, ES2018 for objects."],
            ["Classes", "Syntax over prototypes.", "class User { constructor(n) { this.n = n; } }", "new User('Ana')", "ES2015. Supports extends, super, static, and # private fields."],
            ["Modules", "Splits code across files.", "export const a = 1; import { a } from './a.js';", "Shared code", "ES2015. Use type=\"module\" in the browser."],
            ["Promise", "Represents a future value.", "new Promise((resolve) => resolve(1))", "A pending promise", "ES2015. See the Async sheet for the full picture."],
            ["for...of", "Iterates values of an iterable.", "for (const n of arr) { }", "Each value", "ES2015. for...in walks keys and is rarely what you want on arrays."],
            ["Map and Set", "Keyed and unique collections.", "new Map(); new Set();", "Collections", "ES2015. Real size, any key type, guaranteed order."],
            ["async and await", "Writes asynchronous code sequentially.", "const data = await fetch(url);", "Resolved value", "ES2017. The default style for promises today."],
            ["Object spread", "Copies and merges objects.", "const next = { ...state, done: true };", "New object", "ES2018. The core idiom of immutable state updates."],
            ["Optional chaining", "Short-circuits on null or undefined.", "a?.b?.c", "undefined, no throw", "ES2020."],
            ["Nullish coalescing", "Default only for null or undefined.", "value ?? fallback", "Keeps 0 and ''", "ES2020. Pairs naturally with optional chaining."],
            ["Logical assignment", "Conditional assignment shorthands.", "a ??= 1; b ||= 2; c &&= 3;", "Assigns conditionally", "ES2021."],
            ["Array.at()", "Index access allowing negatives.", "arr.at(-1)", "Last item", "ES2022. Replaces arr[arr.length - 1]."],
            ["Top-level await", "await outside an async function, in modules.", "const cfg = await load();", "Resolved value", "ES2022. Modules only, never in classic scripts."],
        ],
    ),
    (
        "09 Asynchronous JavaScript",
        "Promises, async and await, and the event loop that orders it all.",
        [
            ["Single threaded", "One call stack runs your code.", "while (true) { } // freezes the page", "Everything blocks", "Why long synchronous work makes a UI unresponsive."],
            ["Event loop", "Moves finished work back onto the empty stack.", "setTimeout(f, 0)", "Runs after the current code", "Even a zero delay waits for the stack to clear."],
            ["Microtask vs macrotask", "Promises jump ahead of timers.", "setTimeout(() => log('t')); Promise.resolve().then(() => log('p'));", "p then t", "Promise callbacks drain before the next timer."],
            ["Callback", "A function invoked when work finishes.", "fs.readFile(path, (err, data) => { });", "Called later", "The original async style. Nesting turns into callback hell."],
            ["Promise states", "pending, then fulfilled or rejected.", "const p = fetch(url);", "Pending at first", "Settles exactly once and never changes afterwards."],
            [".then()", "Handles a fulfilled value.", "p.then(res => res.json())", "A new promise", "Returning a value inside then chains it onward."],
            [".catch()", "Handles a rejection.", "p.catch(err => console.error(err))", "Recovers the chain", "Put it at the end so it covers every earlier step."],
            [".finally()", "Runs either way.", "p.finally(() => setLoading(false))", "Cleanup", "Ideal for spinners and closing resources."],
            ["async function", "Always returns a promise.", "async function load() { return 1; }", "Promise resolving to 1", "Even a plain return value gets wrapped."],
            ["await", "Pauses until a promise settles.", "const res = await fetch(url);", "The resolved value", "Only inside an async function, or at the top level of a module."],
            ["try / catch with await", "Handles async errors.", "try { await load(); } catch (e) { }", "Error caught", "The await equivalent of .catch()."],
            ["Promise.all()", "Waits for every promise, fails fast.", "await Promise.all([a, b])", "Array of results", "One rejection rejects the whole thing. Use for parallel loads."],
            ["Promise.allSettled()", "Waits for every promise, never rejects.", "await Promise.allSettled([a, b])", "Array of status objects", "Use when partial failure is acceptable."],
            ["Promise.race()", "Settles with the first one to finish.", "await Promise.race([work, timeout])", "The winner", "The standard timeout pattern."],
            ["Promise.any()", "First fulfilment, ignoring rejections.", "await Promise.any([m1, m2])", "First success", "Rejects only when all of them reject."],
            ["fetch()", "Makes an HTTP request.", "const r = await fetch(url); const d = await r.json();", "Parsed body", "Does not reject on 404 or 500. Check r.ok yourself."],
            ["Sequential vs parallel", "await in a loop serialises the work.", "await Promise.all(urls.map(fetch))", "All at once", "Awaiting inside a for loop is a common performance mistake."],
        ],
    ),
    (
        "10 DOM and Events",
        "Reading, changing, and reacting to the page.",
        [
            ["querySelector()", "First element matching a CSS selector.", "document.querySelector('.card')", "Element or null", "Always check for null before using the result."],
            ["querySelectorAll()", "Every match, as a static NodeList.", "document.querySelectorAll('li')", "NodeList", "Has forEach but not map. Spread it into an array first."],
            ["getElementById()", "Fastest lookup by id.", "document.getElementById('app')", "Element or null", "No # prefix here, unlike querySelector."],
            ["textContent", "Reads or writes text.", "el.textContent = 'Hello';", "Text replaced", "Safe with user input. Prefer it over innerHTML."],
            ["innerHTML", "Reads or writes markup.", "el.innerHTML = '<b>Hi</b>';", "Parsed as HTML", "Injecting untrusted input here is an XSS hole."],
            ["classList", "Adds, removes, or toggles classes.", "el.classList.toggle('active')", "Class flipped", "Cleaner than editing className by hand."],
            ["setAttribute / dataset", "Reads and writes attributes.", "el.dataset.userId = '7';", "data-user-id=\"7\"", "dataset maps data-* attributes to camelCase keys."],
            ["createElement + append", "Builds and inserts nodes.", "const li = document.createElement('li'); ul.append(li);", "Node added", "append accepts several nodes and plain strings."],
            ["remove()", "Detaches an element.", "el.remove()", "Gone from the DOM", "Much simpler than the old parentNode.removeChild."],
            ["addEventListener()", "Subscribes to an event.", "btn.addEventListener('click', onClick)", "Handler registered", "Supports many handlers per event, unlike onclick."],
            ["Event object", "Carries details of what happened.", "el.addEventListener('input', e => e.target.value)", "The current value", "e.target is where it started, e.currentTarget is where it is bound."],
            ["preventDefault()", "Cancels the browser default action.", "form.addEventListener('submit', e => e.preventDefault())", "No page reload", "The first line of nearly every submit handler."],
            ["stopPropagation()", "Stops bubbling to ancestors.", "e.stopPropagation()", "Parents do not fire", "Use sparingly, it can hide real bugs."],
            ["Event delegation", "One listener on a parent handles many children.", "list.addEventListener('click', e => e.target.closest('li'))", "Works for future items", "Efficient, and it covers dynamically added elements."],
            ["DOMContentLoaded", "Fires when the HTML is parsed.", "document.addEventListener('DOMContentLoaded', init)", "init runs", "Unnecessary when your script tag uses defer."],
            ["removeEventListener()", "Unsubscribes a handler.", "el.removeEventListener('click', onClick)", "Handler removed", "Needs the exact same function reference, so no inline arrow."],
        ],
    ),
    (
        "11 Errors and Debugging",
        "Failing loudly in development, and failing gracefully in production.",
        [
            ["try / catch", "Runs code and handles a throw.", "try { risky(); } catch (err) { }", "Error handled", "Only catches synchronous errors, unless you await inside."],
            ["finally", "Runs whether or not it threw.", "try { } catch { } finally { close(); }", "Cleanup guaranteed", "Runs even when the try block returns."],
            ["throw", "Raises an error yourself.", "throw new Error('Missing id');", "Execution stops", "Throw Error objects, not strings, so you keep the stack trace."],
            ["Error types", "Built-in error classes.", "TypeError, ReferenceError, SyntaxError, RangeError", "Different names", "The type usually points straight at the cause."],
            ["Custom errors", "Domain-specific error classes.", "class NotFound extends Error { }", "instanceof NotFound", "Lets a catch block distinguish expected failures."],
            ["Cannot read properties of undefined", "You accessed a property of a missing value.", "user.address.city // address missing", "TypeError", "Fix with optional chaining or an earlier guard."],
            ["x is not a function", "The value is not callable.", "arr.push2()", "TypeError", "Usually a typo or a missing import."],
            ["x is not defined", "The name does not exist in scope.", "console.log(notDeclared)", "ReferenceError", "Typo, wrong scope, or use before declaration in the TDZ."],
            ["Unhandled rejection", "A rejected promise nobody caught.", "fetch(url) // no .catch", "Warning in the console", "Always terminate a chain with catch, or await inside try."],
            ["console.log", "Prints values.", "console.log({ user })", "Logged object", "Wrapping in braces labels the value with its variable name."],
            ["console.table", "Prints arrays of objects as a grid.", "console.table(users)", "A readable table", "Far easier to scan than nested log output."],
            ["debugger", "Pauses in the browser devtools.", "debugger;", "Execution pauses", "Step through and inspect scope. Beats scattering logs."],
            ["Optional catch binding", "Omits the error variable.", "try { } catch { }", "Valid syntax", "ES2019, for when you do not need the error object."],
            ["Fail fast on input", "Validate before doing work.", "if (!Array.isArray(items)) throw new TypeError('items must be an array');", "Clear early error", "A precise message now saves an hour of debugging later."],
        ],
    ),
    (
        "12 Gotchas and Interview Prep",
        "The classics. Being able to explain each one is worth a lot in an interview.",
        [
            ["0.1 + 0.2", "Floating point cannot represent these exactly.", "0.1 + 0.2 === 0.3", "false", "It is 0.30000000000000004. Compare with a small epsilon, or work in integer cents."],
            ["typeof null", "A bug preserved for backwards compatibility.", "typeof null", "'object'", "Test with value === null."],
            ["NaN !== NaN", "NaN is the only value not equal to itself.", "NaN === NaN", "false", "Use Number.isNaN, not the global isNaN, which coerces first."],
            ["Default sort", "sort compares items as strings.", "[10, 9, 1].sort()", "[1, 10, 9]", "Always pass (a, b) => a - b for numbers."],
            ["var in a loop", "One shared binding for every iteration.", "for (var i = 0; i < 3; i++) setTimeout(() => log(i));", "3 3 3", "let creates a fresh binding per iteration and logs 0 1 2."],
            ["const object", "The binding is constant, the contents are not.", "const a = []; a.push(1);", "Works fine", "Only a = somethingElse throws."],
            ["Shallow copy", "Spread copies one level only.", "const c = { ...o };", "Nested objects shared", "Use structuredClone for a real deep copy."],
            ["this in a callback", "A plain function loses its this.", "arr.map(function () { return this.x; })", "undefined", "Use an arrow function, which keeps the outer this."],
            ["Arrays are objects", "typeof cannot detect an array.", "typeof []", "'object'", "Use Array.isArray()."],
            ["[] == false", "Loose equality coerces both sides.", "[] == false", "true", "The single best argument for always using ===."],
            ["Mutating props", "Array methods that change in place.", "sort, reverse, splice, push, pop, shift, unshift", "Original changed", "Copy first with [...arr] when the source must survive."],
            ["forEach and async", "forEach ignores the promises you return.", "arr.forEach(async x => await save(x))", "Does not wait", "Use for...of with await, or Promise.all with map."],
            ["Hoisting", "Declarations move up, initialisations do not.", "console.log(a); var a = 1;", "undefined", "let and const throw instead, thanks to the TDZ."],
            ["Closures in interviews", "Explain private state with a counter.", "function counter() { let c = 0; return () => ++c; }", "1, 2, 3...", "Then explain why the var loop logs 3 3 3."],
            ["Event loop question", "Predict the output order.", "log('1'); setTimeout(() => log('2')); Promise.resolve().then(() => log('3')); log('4');", "1 4 3 2", "Synchronous first, then microtasks, then timers."],
            ["== vs ===", "Know when coercion applies.", "'' == 0 is true, '' === 0 is false", "Different answers", "Use === everywhere except the null check x == null."],
        ],
    ),
]

# Rows for the practice tracker: topic, sheet, difficulty, suggested exercise.
TRACKER_ROWS = [
    ["Variables and Scope", "01 Variables and Scope", "Easy", "Write a counter with a closure and explain why the value survives."],
    ["Types and Coercion", "02 Types and Coercion", "Easy", "List the eight falsy values from memory, then verify each one."],
    ["Operators", "03 Operators", "Easy", "Rewrite three || defaults as ?? and describe what changes."],
    ["Strings", "04 Strings", "Easy", "Build a slug function: lowercase, trim, replace spaces with dashes."],
    ["Arrays: map filter reduce", "05 Arrays", "Medium", "From an array of orders, compute the total for one customer without a for loop."],
    ["Arrays: mutation", "05 Arrays", "Medium", "Sort a list without touching the original array."],
    ["Objects", "06 Objects", "Medium", "Merge defaults with user options, then prove the copy is shallow."],
    ["Destructuring", "06 Objects", "Easy", "Destructure a nested API response with defaults for missing fields."],
    ["Functions and closures", "07 Functions", "Medium", "Write a once(fn) helper that runs its argument only the first time."],
    ["this and binding", "07 Functions", "Hard", "Show the same method losing this, then fix it three different ways."],
    ["Modern syntax", "08 Modern Syntax", "Easy", "Refactor an old ES5 snippet into arrows, const, and template literals."],
    ["Classes and modules", "08 Modern Syntax", "Medium", "Split a script into two modules with named and default exports."],
    ["Promises", "09 Asynchronous JavaScript", "Medium", "Chain three fetches with then, then rewrite it using await."],
    ["async and await", "09 Asynchronous JavaScript", "Medium", "Load five URLs in parallel and handle one of them failing."],
    ["Event loop", "09 Asynchronous JavaScript", "Hard", "Predict the log order of a mixed setTimeout and Promise snippet."],
    ["DOM manipulation", "10 DOM and Events", "Easy", "Render a list from an array, then remove one item on click."],
    ["Events and delegation", "10 DOM and Events", "Medium", "Handle clicks for a list that grows, using a single listener."],
    ["Forms", "10 DOM and Events", "Medium", "Validate a form on submit without letting the page reload."],
    ["Error handling", "11 Errors and Debugging", "Medium", "Wrap a fetch so a 404 throws a custom NotFound error."],
    ["Debugging", "11 Errors and Debugging", "Easy", "Find a planted bug using breakpoints only, with no console.log."],
    ["Interview gotchas", "12 Gotchas and Interview Prep", "Hard", "Explain 0.1 + 0.2, typeof null, and the var loop out loud."],
    ["Mini project", "All sheets", "Hard", "Build a to-do app: render, add, delete, filter, and persist to localStorage."],
]

STATUS_WEIGHTS = [
    ("Not started", 0.0),
    ("Learning", 0.35),
    ("Practising", 0.7),
    ("Confident", 1.0),
]
